---
AllCops:
  Exclude:
    - vendor/**/*
    - bin/**/*
    - .kitchen/**/*
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
NumericLiterals:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Metrics/LineLength:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
